// An unused import required to support JSX, without it this will fail
import React from 'react';

const vendors =  [
    <script defer type='text/javascript' src='/public/js/vendor/pace/pace.js'></script>,
    <script defer type='text/javascript' src='/public/js/polyfills/polyfills.js'></script>,
    <script defer type='text/javascript' src='/public/js/polyfills/html5shiv.js'></script>,
    <script defer type='text/javascript' src='/public/js/polyfills/modernizr.min.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/codemirror/lib/codemirror.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/codemirror/mode/javascript/javascript.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/eventemitter2/eventemitter2.min.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/jquery/jquery.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/jquery-ui/jquery-ui.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/bootstrap/bootstrap.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/p-scrollbar/min/perfect-scrollbar.min.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/ion.tabs/ion.tabs.min.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/ion.rangeSlider/ion.rangeSlider.min.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/bootstrap-slider/bootstrap-slider.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/sparklines/sparklines.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/jquery.knob/jquery.knob.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/moment/moment.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/vex/vex.min.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/messenger/messenger.min.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/select2/select2.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/xeditable/xeditable.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/typeahead/typeahead.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/jquery-steps/jquery-steps.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/jquery-validate/jquery-validate.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/tablesaw/tablesaw.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/timeline/timeline.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/datatables/datatables.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/fullcalendar/fullcalendar.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/nestable/nestable.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/dropzone/dropzone.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/jcrop/color.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/jcrop/jcrop.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/blueimp-gallery/blueimp-gallery.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/chartjs/chartjs.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/c3js/c3js.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/leaflet/leaflet.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/trumbowyg/trumbowyg.js'></script>,
    <script defer type='text/javascript' src='/public/js/common/react/react.js'></script>,
    <script defer type='text/javascript' src='/public/js/common/react-router/react-router.js'></script>,
    <script defer type='text/javascript' src='/public/js/common/react-bootstrap/react-bootstrap.js'></script>,
    <script defer type='text/javascript' src='/public/js/common/react-l20n/react-l20n.js'></script>,
    <script defer type='text/javascript' src='/public/js/common/react-responsive/react-responsive.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/d3/d3.js'></script>,
    <script defer type='text/javascript' src='/public/js/common/rubix/rubix.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/raphael/raphael.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/morris/morris.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/prism/prism.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/switchery/switchery.js'></script>,
    <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=true"></script>,
    <script type='text/javascript' src='/public/js/vendor/gmaps/gmaps.js'></script>,
    <script defer type='text/javascript' src='/public/js/vendor/holder/holder.js'></script>,
    <script defer type='text/javascript' src='/public/js/common/react/showdown.js'></script>
];

export default vendors;
